name: Update mirror

on:
  push:
    branches:
      - automation
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '42 */3 * * *'
  workflow_dispatch: # allows to be run manually

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          ref: automation
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            !~/.cache/pip/log/debug.log
            ~/.local/bin
          key: ${{ runner.os }}_pip_${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}_pip_
      - name: Install dependencies
        run: pip install --user -r requirements.txt
      - name: Cache Mercurial repository clone - prepare cache key parts
        id: cache_date
        run: |
          echo ::set-output name=YEAR::$(date +"%Y")
          echo ::set-output name=MONTH::$(date +"%m")
          echo ::set-output name=DAY::$(date +"%d")
      - name: Cache Mercurial repository clone
        uses: actions/cache@v3
        with:
          path: |
            github_l10n-mozilla-central-cs
            !github_l10n-mozilla-central-cs/.hg/hgrc
          key: ${{ runner.os }}_hg-repository_${{ steps.cache_date.outputs.YEAR }}_${{ steps.cache_date.outputs.MONTH }}_${{ steps.cache_date.outputs.DAY }}
          restore-keys: |
            ${{ runner.os }}_hg-repository_${{ steps.cache_date.outputs.YEAR }}_${{ steps.cache_date.outputs.MONTH }}_
      - name: Update mirror
        run: bash ./mirror-hg-to-git.sh 'https://hg.mozilla.org/l10n-central/cs/' 'https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git'
        working-directory: github_l10n-mozilla-central-cs
